# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    io_and_status_controller:
      type: ur_controllers/GPIOController


    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster


    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster


    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController


    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


    forward_position_controller:
      type: position_controllers/JointGroupPositionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

io_and_status_controller:
  ros__parameters:
    joints:
      []
speed_scaling_state_broadcaster:
  ros__parameters:
    joints:
      []
force_torque_sensor_broadcaster:
  ros__parameters:
    joints:
      []
scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur20_shoulder_pan_joint
      - ur20_shoulder_lift_joint
      - ur20_elbow_joint
      - ur20_wrist_1_joint
      - ur20_wrist_2_joint
      - ur20_wrist_3_joint
forward_velocity_controller:
  ros__parameters:
    joints:
      - ur20_shoulder_pan_joint
      - ur20_shoulder_lift_joint
      - ur20_elbow_joint
      - ur20_wrist_1_joint
      - ur20_wrist_2_joint
      - ur20_wrist_3_joint
forward_position_controller:
  ros__parameters:
    joints:
      - ur20_shoulder_pan_joint
      - ur20_shoulder_lift_joint
      - ur20_elbow_joint
      - ur20_wrist_1_joint
      - ur20_wrist_2_joint
      - ur20_wrist_3_joint